# randomstream - stream of pseudo random numbers
# Copyright (C) 2018 Ingo Ruhnke <grumbel@gmail.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

image: ubuntu:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - apt-get -qq update
  - apt-get -qq -y install lsb-release
  - lsb_release -a
  - apt-get -qq -y install
    clang-6.0
    g++-8
    cmake
    build-essential
    libc++-dev
    software-properties-common

.build_randomstream_template: &build_randomstream
  stage: build
  script:
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DWARNINGS=ON -DWERROR=ON
    - make VERBOSE=1

build:gcc:release:
  <<: *build_randomstream
  variables:
    CXX: g++-8
    BUILD_TYPE: Release

build:clang:release:
  <<: *build_randomstream
  variables:
    CXX: clang++-6.0
    BUILD_TYPE: Release

build:gcc:debug:
  <<: *build_randomstream
  variables:
    CXX: g++-8
    BUILD_TYPE: Debug

build:clang:debug:
  <<: *build_randomstream
  variables:
    CXX: clang++-6.0
    BUILD_TYPE: Debug

build:flatpak:
  stage: build
  script:
    - add-apt-repository -y ppa:alexlarsson/flatpak
    - apt-get -qq update
    - apt-get -qq -y install flatpak flatpak-builder
    - flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
    - flatpak install -y flathub org.freedesktop.Platform org.freedesktop.Sdk
    - flatpak-builder --repo=build-flatpak-repo/ build-flatpak/ org.grumbel.randomstream.json randomstream
    - flatpak build-bundle build-flatpak-repo/ randomstream.flatpak org.grumbel.randomstream
  artifacts:
    paths:
      - randomstream.flatpak
      - build-flatpak-repo

pages:
  dependencies:
    - build:flatpak
  stage: deploy
  script:
    - mkdir public.tmp/
    - mv -v build-flatpak-repo public.tmp/flatpak
    - mv -vi public.tmp public

# EOF #
